/** Map full MLB club names (and a few aliases) → standard abbreviations. */
const NAME_TO_ABBR: Record<string, string> = {
  'Arizona Diamondbacks': 'AZ',
  'Athletics': 'ATH',
  'Atlanta Braves': 'ATL',
  'Baltimore Orioles': 'BAL',
  'Boston Red Sox': 'BOS',
  'Chicago Cubs': 'CHC',
  'Chicago White Sox': 'CWS',
  'Cincinnati Reds': 'CIN',
  'Cleveland Guardians': 'CLE',
  'Colorado Rockies': 'COL',
  'Detroit Tigers': 'DET',
  'Houston Astros': 'HOU',
  'Kansas City Royals': 'KC',
  'Los Angeles Angels': 'LAA',
  'Los Angeles Dodgers': 'LAD',
  'Miami Marlins': 'MIA',
  'Milwaukee Brewers': 'MIL',
  'Minnesota Twins': 'MIN',
  'New York Mets': 'NYM',
  'New York Yankees': 'NYY',
  'Philadelphia Phillies': 'PHI',
  'Pittsburgh Pirates': 'PIT',
  'San Diego Padres': 'SD',
  'San Francisco Giants': 'SF',
  'Seattle Mariners': 'SEA',
  'St. Louis Cardinals': 'STL',
  'Tampa Bay Rays': 'TB',
  'Texas Rangers': 'TEX',
  'Toronto Blue Jays': 'TOR',
  'Washington Nationals': 'WSH',
};

const KNOWN_ABBR = new Set([
  'AZ',
  'ARI',
  'ATH',
  'OAK',
  'ATL',
  'BAL',
  'BOS',
  'CHC',
  'CWS',
  'CHW',
  'CIN',
  'CLE',
  'COL',
  'DET',
  'HOU',
  'KC',
  'KCR',
  'LAA',
  'LAD',
  'MIA',
  'MIL',
  'MIN',
  'NYM',
  'NYY',
  'PHI',
  'PIT',
  'SD',
  'SDP',
  'SF',
  'SFG',
  'SEA',
  'STL',
  'TB',
  'TBR',
  'TEX',
  'TOR',
  'WSH',
  'WSN',
]);

/** Resolve a game-log opponent string (abbr or full name) to a logo abbr. */
export function opponentAbbr(raw?: string | null): string {
  if (!raw) return 'ATL';
  const trimmed = raw.trim();
  if (KNOWN_ABBR.has(trimmed.toUpperCase())) return trimmed.toUpperCase();
  return NAME_TO_ABBR[trimmed] || trimmed.slice(0, 3).toUpperCase();
}
